### ISSUE TITLE
Why was Android platform removed? 

### ISSUE THREAD

**Issue by charlesmccann** [commontime/com.commontime.cordova.authentication#1]
Why was it removed?  referencing this change / comment: https://github.com/commontime/com.commontime.cordova.authentication/commit/758634a63a30f77dcaa226a0b3c66c887bd28105

When will it be added back in?

**Comment by RevillWeb** [comment]
Hi,

We are not currently supporting this plugin, it is only used for internal use. However, we will be adding Android support back in the near future.

**Comment by charlesmccann** [comment]
Thanks for the follow-up.  If the plugin isn't supported, should the README be updated accordingly?
